### PR TITLE
Adding registration-harvester-api as a flowable app

### PR DESCRIPTION
**Pull request by constantinius**

### CODE REVIEW

**Comment by constantinius** [comment]
Addresses https://github.com/EOEPCA/resource-registration/issues/29

**Comment by constantinius** [comment]
TODO: Database credentials should come from a secret.

**Comment by rconway** [comment]
@james-hinton Can you take a quick review of this - and provide feedback to Fabian.

**Comment by james-hinton** [comment]
> TODO: Database credentials should come from a secret.

We can use Sealed Secrets for this, I can write a short guide if that's useful for you?

**Review by james-hinton — APPROVED** [review]
This all looks good and follows our structure for other BBs. I'm happy to merge this and we can see if it works, shall we go ahead with that?

**Comment by james-hinton** [comment]
The pods seem to be running fine, if there's any further questions I can be on hand to help out.

**Pull request merged**
