### PR TITLE
Protect harbor with sealed secrets.

### PR DESCRIPTION
**Pull request by pantierra**
This PR switches harbor's root user authentication to sealed secrets.

Related to https://github.com/EOEPCA/data-access/issues/82

### CODE REVIEW

**Comment by pantierra** [comment]
Marked as draft, because this is untested so far. You may want to have a look already, @jankovicgd.

**Comment by pantierra** [comment]
Completed this PR, but still untested.

**Comment by j08lue** [comment]
Awesome, @pantierra! How do we test this? If it is easiest, it would be fine to merge this (after review from @jankovicgd) and deploy to develop - that is what it is for...

**Review by rconway — APPROVED** [review]
Suggest to commit to cluster

**Pull request merged**
